import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Icon from '../components/Icon'
// import { faCookieBite } from '@fortawesome/free-solid-svg-icons'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const Router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Floot is loot for recipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="text-orange-500">Floot </span> is loot for recipe 
        </h1>
        <button onClick={() => Router.push('/traits')}>click</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
