import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const Router = useRouter()
  return (
    <div className="md:w-3/5 w-5/6 m-auto flex flex-col justify-start">
      <Head>
        <title>Floot is loot for recipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:w-3/5 w-5/6 m-auto flex flex-col justify-start">
        <div className="flex justify-between">
          <div className="text-4xl mb-2 font-bold">
            <button className="w-64 p-3 border-black border-4 text-xl font-bold" onClick={() => Router.push('/')}>Back Design</button>
          </div>
          <div className="text-2xl mb-2">
            <h1 className="text-4xl mb-2 font-bold">
              Floot Traits
            </h1>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
