import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const Router = useRouter()
  return (
    <div className="md:w-3/5 w-5/6 m-auto flex flex-col justify-start">
      <Head>
        <title>Floot is loot for recipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full m-auto flex flex-col justify-start mt-2">
        <div className="flex justify-between">
          <div className="text-4xl mb-2 font-bold">
            <button className="w-64 p-3 border-black border-4 text-xl font-bold" onClick={() => Router.push('/')}>Back Design</button>
          </div>
          <div className="text-2xl mb-2">
            <h1 className="text-4xl mb-2 font-bold">
              Floot Traits
            </h1>
          </div>
        </div>
        <span className="w-full h-3 bg-black mb-2"></span>
      </main>
      <div className="grid-cols-3 grid w-full">
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
        <img src="https://portlandenglish.edu/wp-content/uploads/2015/02/500x5001.gif" className="mx-2 my-2" />
      </div>
    </div>
  )
}

export default Home
